version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '04:00'
      timezone: 'Asia/Taipei'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
    reviewers:
      - 'cowcfj'
    groups:
      linters:
        patterns:
          - 'eslint*'
          - 'prettier'
      babel:
        patterns:
          - '@babel/*'
      rollup:
        patterns:
          - 'rollup'
          - '@rollup/plugin-*'
      testing:
        patterns:
          - 'jest*'
          - '@playwright/test'
          - 'puppeteer'
    ignore:
      - dependency-name: 'puppeteer'
        update-types: ['version-update:semver-major']
      - dependency-name: '@playwright/test'
        update-types: ['version-update:semver-major']
      - dependency-name: 'jest'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '04:30'
      timezone: 'Asia/Taipei'
    open-pull-requests-limit: 2
    labels:
      - 'dependencies'
