# CodeRabbit Configuration
# Documentation: https://coderabbit.ai/docs/configure-coderabbit

language: 'zh'

reviews:
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: false
  review_status: false
  auto_review:
    enabled: true
    ignore_usernames:
      - 'release-please[bot]'
      - 'github-actions[bot]'
  path_filters:
    - '!CHANGELOG.md'
    - '!package-lock.json'
    - '!dist/**'
    - '!coverage/**'
    - '!icons/**'
    - '!promo-images/**'
    - '!releases/**'
    - '!demos/**'
    - '!docs/guides/*_MCP_GUIDE.md'
    - '!docs/guides/CONTEXT7_MCP_GUIDE.md'
