# Codecov Configuration
# 文檔: https://docs.codecov.com/docs/codecov-yaml
# 最後更新: 2025-12-20 - 清理 testable 檔案後更新

# 覆蓋率設置
coverage:
  # 覆蓋率變化閾值
  status:
    project:
      default:
        target: 28% # 目標覆蓋率
        threshold: 2% # 允許的下降幅度
        if_ci_failed: error # CI 失敗時的行為
    patch:
      default:
        target: 40% # 新代碼的目標覆蓋率
        threshold: 5%

  # 精確度設置
  precision: 2 # 小數位數
  round: down # 向下取整
  range: '20...100' # 顏色範圍（20% 以下紅色，100% 綠色）

# 註釋設置
comment:
  layout: 'reach,diff,flags,tree,files'
  behavior: default # 默認行為：如果有變化則註釋
  require_changes: true # 只在覆蓋率變化時註釋

# 忽略的文件和目錄
ignore:
  - 'tests/**/*.test.js' # 測試文件本身
  - 'tests/**/*.spec.js'
  - 'tests/helpers/**' # 測試輔助工具（非生產代碼）
  - 'node_modules/**'
  - 'archive/**'
  - 'internal/**'
  - 'demos/**'
  - 'promo-images/**'
  - 'build/**'
  - 'dist/**' # Rollup 打包後的文件(避免重複計算覆蓋率)

# Flags 配置（用於追蹤不同類型的測試）
flags:
  unittests:
    paths:
      - scripts/
    carryforward: true # 保留先前的覆蓋率數據

# 說明：
# - 所有生產代碼位於 scripts/ 目錄
# - tests/helpers/ 僅包含測試工具（如 mock helpers），不計入覆蓋率
# - 2025-12-20: 清理遺留的 *.testable.js 檔案
