# Codecov Configuration
# 文檔: https://docs.codecov.com/docs/codecov-yaml
# 最後更新: 2025-12-20 - 清理 testable 檔案後更新

# 覆蓋率設置
coverage:
  # 覆蓋率變化閾值
  status:
    project:
      default:
        target: 28% # 目標覆蓋率
        threshold: 2% # 允許的下降幅度
        if_ci_failed: error # CI 失敗時的行為
    patch:
      default:
        target: 40% # 新代碼的目標覆蓋率
        threshold: 5%

  # 精確度設置
  precision: 2 # 小數位數
  round: down # 向下取整
  range: '20...100' # 顏色範圍（20% 以下紅色，100% 綠色）

# 註釋設置
comment:
  layout: 'reach,diff,flags,tree,files'
  behavior: default # 默認行為：如果有變化則註釋
  require_changes: true # 只在覆蓋率變化時註釋

# 忽略的文件和目錄
# 注意：Codecov 不支持 brace expansion，無法使用 {test,spec} 語法，需分開列出
ignore:
  - 'tests/**/*.test.js' # 單元測試文件
  - 'tests/**/*.spec.js' # E2E 測試文件
  - 'tests/helpers/**' # 測試輔助工具（非生產代碼）
  - 'node_modules/**'
  - 'archive/**'
  - 'internal/**'
  - 'demos/**'
  - 'promo-images/**'
  - 'build/**'
  - 'dist/**' # Rollup 打包後的文件(避免重複計算覆蓋率)

# Flags 配置（用於追蹤不同類型的測試）
flags:
  unittests:
    paths:
      - scripts/
    carryforward: true # 保留先前的覆蓋率數據

# 說明：
# - 所有生產代碼位於 scripts/ 目錄
# - tests/helpers/ 僅包含測試工具（如 mock helpers），不計入覆蓋率
#
# 覆蓋率歷史變更：
# - 2025-12-20: 移除 *.testable.js 檔案及其單元測試
#   - 這些檔案原本是從 scripts/ 提取的可測試邏輯副本
#   - 重構後生產代碼已模組化，testable 副本成為冗餘
#   - 刪除約 2,600 行重複測試代碼
#
#   現有生產模組測試（直接測試 scripts/ 目錄下的模組）：
#   - scripts/utils/Logger.js       → tests/unit/utils/Logger.test.js (418 行)
#   - scripts/utils/urlUtils.js     → tests/unit/normalizeUrl.test.js (148 行)
#   - scripts/highlighter/utils/StorageUtil.js →
#       - tests/unit/utils.test.js (256 行)
#       - tests/unit/storageUtil.test.js (948 行)
#
#   測試總行數：被刪除 ~700 行（舊副本）→ 現有 ~1,770 行（生產模組直接測試）
#   整體覆蓋率目標維持 28%（僅追蹤 scripts/ 目錄）

