# Codecov Configuration
# 文檔: https://docs.codecov.com/docs/codecov-yaml

# 覆蓋率設置
coverage:
  # 覆蓋率變化閾值
  status:
    project:
      default:
        target: auto  # 目標覆蓋率（auto = 自動適應）
        threshold: 1%  # 允許的下降幅度
        if_ci_failed: error  # CI 失敗時的行為
    patch:
      default:
        target: 50%  # 新代碼的目標覆蓋率
        threshold: 5%
  
  # 精確度設置
  precision: 2  # 小數位數
  round: down  # 向下取整
  range: "70...100"  # 顏色範圍（70% 以下紅色，100% 綠色）

# 註釋設置
comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default  # 默認行為：如果有變化則註釋
  require_changes: true  # 只在覆蓋率變化時註釋

# 忽略的文件和目錄
ignore:
  - "tests/**/*.test.js"  # 測試文件本身
  - "**/*.spec.js"
  - "node_modules/**"
  - "archive/**"
  - "internal/**"
  - "demos/**"
  - "promo-images/**"
  - "build/**"
  - "coverage/**"
  # 注意：不忽略 tests/helpers/*.testable.js，因為這些是可測試的實際代碼

# Flags 配置（用於追蹤不同類型的測試）
flags:
  unittests:
    paths:
      - scripts/
      - tests/helpers/
    carryforward: true  # 保留先前的覆蓋率數據

# 說明：
# - scripts/ 包含實際的 Chrome Extension 代碼（大部分依賴 Chrome API，難以測試）
# - tests/helpers/*.testable.js 包含從 scripts/ 提取的可測試邏輯
# - 兩者都計入覆蓋率，因為 testable.js 文件是實際業務邏輯的純函數版本
