'use strict';

module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  testMatch: ['<rootDir>/tests/native-esm/**/*.test.mjs'],
  transform: {},
  cacheDirectory: '<rootDir>/.tmp/jest-cache-native-esm',
  coverageProvider: 'v8',
  coverageDirectory: '<rootDir>/coverage/native-esm',
  coverageReporters: ['json', 'text'],
  collectCoverageFrom: [
    '<rootDir>/scripts/background.js',
    '<rootDir>/scripts/content/index.js',
    '<rootDir>/pages/options/options.js',
    '<rootDir>/pages/sidepanel/sidepanel.js',
    '<rootDir>/pages/popup/popup.js',
    '<rootDir>/scripts/background/handlers/MessageHandler.js',
    '<rootDir>/scripts/background/handlers/saveHandlers.js',
    '<rootDir>/scripts/background/handlers/notionHandlers.js',
    '<rootDir>/scripts/background/handlers/driveSyncHandlers.js',
    '<rootDir>/scripts/background/services/InjectionService.js',
    '<rootDir>/scripts/background/services/NotionService.js',
    '<rootDir>/scripts/background/services/StorageService.js',
    '<rootDir>/scripts/background/services/TabService.js',
    '<rootDir>/pages/options/AuthManager.js',
    '<rootDir>/pages/options/StorageManager.js',
    '<rootDir>/pages/options/UIManager.js',
    '<rootDir>/pages/options/DataSourceManager.js',
    '<rootDir>/pages/sidepanel/sidepanel-storage.js',
    '<rootDir>/pages/sidepanel/sidepanel-unsynced-view.js',
    '<rootDir>/pages/sidepanel/sidepanelUI.js',
    '<rootDir>/pages/popup/popupActions.js',
    '<rootDir>/scripts/auth/accountSession.js',
    '<rootDir>/scripts/auth/accountLogin.js',
    '<rootDir>/scripts/auth/driveClient.js',
    '<rootDir>/scripts/auth/notionOAuthCompleter.js',
    '<rootDir>/scripts/auth/notionOAuthInitiator.js',
    '<rootDir>/scripts/content/extractors/ContentExtractor.js',
    '<rootDir>/scripts/content/extractors/ImageCollector.js',
    '<rootDir>/scripts/content/extractors/ReadabilityAdapter.js',
    '<rootDir>/scripts/content/converters/DomConverter.js',
    '<rootDir>/scripts/content/converters/ContentBridge.js',
    '<rootDir>/scripts/background/utils/BlockBuilder.js',
    '<rootDir>/scripts/background/utils/highlightStyleMerger.js',
    '<rootDir>/scripts/background/utils/migrationMetadataUtils.js',
    '<rootDir>/scripts/config/messages/highlighterMessages.js',
    '<rootDir>/scripts/config/runtimeActions/highlighterActions.js',
    '<rootDir>/scripts/config/shared/content.js',
    '<rootDir>/scripts/config/shared/deepFreeze.js',
    '<rootDir>/scripts/config/shared/saveStatus.js',
    '<rootDir>/scripts/config/shared/storage.js',
    '<rootDir>/scripts/highlighter/autoInit/initializationInputs.js',
    '<rootDir>/scripts/highlighter/utils/color.js',
    '<rootDir>/scripts/highlighter/utils/dom.js',
    '<rootDir>/scripts/highlighter/utils/domStability.js',
    '<rootDir>/scripts/highlighter/utils/path.js',
    '<rootDir>/scripts/highlighter/utils/safeIcon.js',
    '<rootDir>/scripts/highlighter/utils/textSearch.js',
    '<rootDir>/scripts/highlighter/utils/validation.js',
    '<rootDir>/scripts/utils/image/imageAttributeSource.js',
    '<rootDir>/scripts/utils/image/imageBackgroundSource.js',
    '<rootDir>/scripts/utils/image/imageBlockMerge.js',
    '<rootDir>/scripts/utils/image/imageNoscriptSource.js',
    '<rootDir>/scripts/utils/image/imagePictureSource.js',
    '<rootDir>/scripts/utils/image/imageUrl.js',
    '<rootDir>/scripts/utils/image/srcsetCandidateParser.js',
    '<rootDir>/scripts/utils/image/srcsetExtractor.js',
    '<rootDir>/scripts/utils/image/srcsetParserAdapter.js',
    '<rootDir>/scripts/utils/image/srcsetUrlValidator.js',
    '<rootDir>/pages/update-notification/update-notification.js',
  ],
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
  verbose: false,
};
