'use strict';

module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  testMatch: ['<rootDir>/tests/native-esm/**/*.test.mjs'],
  transform: {},
  cacheDirectory: '<rootDir>/.tmp/jest-cache-native-esm',
  coverageProvider: 'v8',
  coverageDirectory: '<rootDir>/coverage/native-esm',
  coverageReporters: ['json', 'text'],
  collectCoverageFrom: [
    '<rootDir>/scripts/background/utils/BlockBuilder.js',
    '<rootDir>/scripts/background/utils/highlightStyleMerger.js',
    '<rootDir>/scripts/background/utils/migrationMetadataUtils.js',
    '<rootDir>/scripts/config/messages/highlighterMessages.js',
    '<rootDir>/scripts/config/runtimeActions/highlighterActions.js',
    '<rootDir>/scripts/config/shared/content.js',
    '<rootDir>/scripts/config/shared/deepFreeze.js',
    '<rootDir>/scripts/config/shared/saveStatus.js',
    '<rootDir>/scripts/config/shared/storage.js',
    '<rootDir>/scripts/highlighter/autoInit/initializationInputs.js',
    '<rootDir>/scripts/highlighter/utils/color.js',
    '<rootDir>/scripts/highlighter/utils/dom.js',
    '<rootDir>/scripts/highlighter/utils/domStability.js',
    '<rootDir>/scripts/highlighter/utils/path.js',
    '<rootDir>/scripts/highlighter/utils/safeIcon.js',
    '<rootDir>/scripts/highlighter/utils/textSearch.js',
    '<rootDir>/scripts/highlighter/utils/validation.js',
    '<rootDir>/scripts/utils/image/imageAttributeSource.js',
    '<rootDir>/scripts/utils/image/imageBackgroundSource.js',
    '<rootDir>/scripts/utils/image/imageBlockMerge.js',
    '<rootDir>/scripts/utils/image/imageNoscriptSource.js',
    '<rootDir>/scripts/utils/image/imagePictureSource.js',
    '<rootDir>/scripts/utils/image/imageUrl.js',
    '<rootDir>/scripts/utils/image/srcsetCandidateParser.js',
    '<rootDir>/scripts/utils/image/srcsetExtractor.js',
    '<rootDir>/scripts/utils/image/srcsetParserAdapter.js',
    '<rootDir>/scripts/utils/image/srcsetUrlValidator.js',
  ],
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
  verbose: false,
};
