'use strict';

module.exports = {
  rootDir: '.',
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    url: 'https://notion-chrome.test/',
  },
  transform: {},
  transformIgnorePatterns: [],
  testMatch: [
    '<rootDir>/tests/native-esm/background/handlers/backgroundHandlers.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/background/services/backgroundServices.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/background/support/background-support-native-siblings.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/background/utils/backgroundUtils.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/config/configConstants.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/destinations/destinations.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/highlighter/utils/domText.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/highlighter/utils/pureUtils.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/utils/root-url-and-page-complexity.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/utils/root-utils-runtime.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/utils/rootUtils.native-esm.test.mjs',
    '<rootDir>/tests/contract/ci/ciPolicyContract.test.mjs',
    '<rootDir>/tests/contract/ci/nativeDefaultRunnerContract.test.mjs',
    '<rootDir>/tests/contract/ci/report-native-default-runner-blockers.test.mjs',
    '<rootDir>/tests/contract/module-surfaces/RetryManager.contract.test.mjs',
    '<rootDir>/tests/integration/background/background-require.integration.test.mjs',
    '<rootDir>/tests/integration/helpers/integration-test-helper.test.mjs',
    '<rootDir>/tests/unit/background/core-functions.test.js',
    '<rootDir>/tests/unit/background/image-processing.test.js',
    '<rootDir>/tests/unit/config/messages.test.js',
    '<rootDir>/tests/unit/config/storageKeys.test.js',
    '<rootDir>/tests/unit/config/auth.callback-page.test.js',
    '<rootDir>/tests/unit/config/coverageExclusionsContract.test.js',
    '<rootDir>/tests/unit/config/env.test.mjs',
    '<rootDir>/tests/unit/config/manifest.auth.test.js',
    '<rootDir>/tests/unit/config/manifest.permissions.test.js',
    '<rootDir>/tests/unit/helpers/performanceOptimizerTestHarness.test.mjs',
    '<rootDir>/tests/unit/helpers/storageServiceTestHarness.test.mjs',
    '<rootDir>/tests/unit/highlighter/highlighter-path-compression.test.js',
    '<rootDir>/tests/unit/highlighter/highlighter-storage-optimization.test.js',
    '<rootDir>/tests/unit/normalizeUrl.test.js',
    '<rootDir>/tests/unit/background/buildHighlightBlocks.test.js',
    '<rootDir>/tests/unit/performance/PerformanceOptimizer.comprehensive.test.mjs',
    '<rootDir>/tests/unit/scripts/assert-native-esm-line-hits.test.mjs',
    '<rootDir>/tests/unit/scripts/check-message-boundaries.test.js',
    '<rootDir>/tests/unit/scripts/check-size-gates.test.mjs',
    '<rootDir>/tests/unit/scripts/inject-manifest-key.test.mjs',
    '<rootDir>/tests/unit/scripts/package-extension.test.mjs',
    '<rootDir>/tests/unit/scripts/postinstall.test.js',
    '<rootDir>/tests/unit/scripts/report-native-esm-scope-parity.test.mjs',
    '<rootDir>/tests/unit/scripts/report-native-esm-threshold-simulation.test.mjs',
    '<rootDir>/tests/unit/utils.dateFormat.test.js',
    '<rootDir>/tests/unit/utils/chrome-mock.test.js',
    '<rootDir>/tests/unit/utils/css-color-mock-shape.test.js',
  ],
  setupFiles: ['<rootDir>/tests/native-esm/native-runner.setup.mjs'],
  setupFilesAfterEnv: ['<rootDir>/tests/native-esm/native-default.after-env.mjs'],
  moduleNameMapper: {
    '^@asamuzakjp/css-color$': '<rootDir>/tests/mocks/css-color.js',
  },
  cacheDirectory: '<rootDir>/.tmp/jest-cache-native-default',
  maxWorkers: 4,
  verbose: false,
};
