'use strict';

module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  testMatch: ['<rootDir>/tests/native-esm/**/*.test.mjs'],
  transform: {},
  cacheDirectory: '<rootDir>/.tmp/jest-cache-native-esm',
  coverageProvider: 'v8',
  coverageDirectory: '<rootDir>/coverage/native-esm',
  coverageReporters: ['json', 'text'],
  collectCoverageFrom: [
    '<rootDir>/scripts/background.js',
    '<rootDir>/scripts/content/index.js',
    '<rootDir>/pages/options/options.js',
    '<rootDir>/pages/sidepanel/sidepanel.js',
    '<rootDir>/pages/popup/popup.js',
    '<rootDir>/scripts/background/handlers/MessageHandler.js',
    '<rootDir>/scripts/background/handlers/saveHandlers.js',
    '<rootDir>/scripts/background/handlers/notionHandlers.js',
    '<rootDir>/scripts/background/handlers/driveSyncHandlers.js',
    '<rootDir>/scripts/background/services/InjectionService.js',
    '<rootDir>/scripts/background/services/NotionService.js',
    '<rootDir>/scripts/background/services/StorageService.js',
    '<rootDir>/scripts/background/services/TabService.js',
    '<rootDir>/pages/onboarding/onboarding.js',
    '<rootDir>/pages/onboarding/onboardingController.js',
    '<rootDir>/pages/options/AuthManager.js',
    '<rootDir>/pages/options/StorageManager.js',
    '<rootDir>/pages/options/UIManager.js',
    '<rootDir>/pages/options/DataSourceManager.js',
    '<rootDir>/pages/sidepanel/sidepanel-storage.js',
    '<rootDir>/pages/sidepanel/sidepanel-unsynced-view.js',
    '<rootDir>/pages/sidepanel/sidepanelUI.js',
    '<rootDir>/pages/popup/popupActions.js',
    '<rootDir>/scripts/auth/accountSession.js',
    '<rootDir>/scripts/auth/accountLogin.js',
    '<rootDir>/scripts/auth/driveClient.js',
    '<rootDir>/scripts/auth/notionOAuthCompleter.js',
    '<rootDir>/scripts/auth/notionOAuthInitiator.js',
    '<rootDir>/scripts/content/extractors/ContentExtractor.js',
    '<rootDir>/scripts/content/extractors/ImageCollector.js',
    '<rootDir>/scripts/content/extractors/ReadabilityAdapter.js',
    '<rootDir>/scripts/content/converters/DomConverter.js',
    '<rootDir>/scripts/content/converters/ContentBridge.js',
    '<rootDir>/scripts/background/utils/BlockBuilder.js',
    '<rootDir>/scripts/background/utils/highlightStyleMerger.js',
    '<rootDir>/scripts/background/utils/migrationMetadataUtils.js',
    '<rootDir>/scripts/config/contentSafe/toolbarIcons.js',
    '<rootDir>/scripts/config/contentSafe/toolbarSelectors.js',
    '<rootDir>/scripts/config/env/build.example.js',
    '<rootDir>/scripts/config/env/build.js',
    '<rootDir>/scripts/config/env/index.js',
    '<rootDir>/scripts/config/env/runtime.js',
    '<rootDir>/scripts/config/messages/backgroundMessages.js',
    '<rootDir>/scripts/config/messages/dataSourceMessages.js',
    '<rootDir>/scripts/config/messages/errorMessages.js',
    '<rootDir>/scripts/config/messages/extractionFallbackMessages.js',
    '<rootDir>/scripts/config/messages/highlighterMessages.js',
    '<rootDir>/scripts/config/messages/runtimeErrorMessages.js',
    '<rootDir>/scripts/config/runtimeActions/authActions.js',
    '<rootDir>/scripts/config/runtimeActions/contentBridgeActions.js',
    '<rootDir>/scripts/config/runtimeActions/diagnosticsActions.js',
    '<rootDir>/scripts/config/runtimeActions/driveSyncActions.js',
    '<rootDir>/scripts/config/runtimeActions/highlighterActions.js',
    '<rootDir>/scripts/config/runtimeActions/migrationActions.js',
    '<rootDir>/scripts/config/runtimeActions/pageSaveActions.js',
    '<rootDir>/scripts/config/runtimeActions/preloaderActions.js',
    '<rootDir>/scripts/config/shared/content.js',
    '<rootDir>/scripts/config/shared/core.js',
    '<rootDir>/scripts/config/shared/deepFreeze.js',
    '<rootDir>/scripts/config/shared/highlightConstants.js',
    '<rootDir>/scripts/config/shared/index.js',
    '<rootDir>/scripts/config/shared/messages.js',
    '<rootDir>/scripts/config/shared/notionCodeLanguages.js',
    '<rootDir>/scripts/config/shared/runtimeActions.js',
    '<rootDir>/scripts/config/shared/saveStatus.js',
    '<rootDir>/scripts/config/shared/storage.js',
    '<rootDir>/scripts/config/shared/technicalTerms.js',
    '<rootDir>/scripts/config/shared/ui.js',
    '<rootDir>/scripts/highlighter/autoInit/initializationInputs.js',
    '<rootDir>/scripts/highlighter/utils/color.js',
    '<rootDir>/scripts/highlighter/utils/dom.js',
    '<rootDir>/scripts/highlighter/utils/domStability.js',
    '<rootDir>/scripts/highlighter/utils/path.js',
    '<rootDir>/scripts/highlighter/utils/safeIcon.js',
    '<rootDir>/scripts/highlighter/utils/textSearch.js',
    '<rootDir>/scripts/highlighter/utils/validation.js',
    '<rootDir>/scripts/utils/image/imageAttributeSource.js',
    '<rootDir>/scripts/utils/image/imageAnchorSource.js',
    '<rootDir>/scripts/utils/image/imageBackgroundSource.js',
    '<rootDir>/scripts/utils/image/imageBlockMerge.js',
    '<rootDir>/scripts/utils/image/imageNoscriptSource.js',
    '<rootDir>/scripts/utils/image/imagePictureSource.js',
    '<rootDir>/scripts/utils/image/imageSourceExtractor.js',
    '<rootDir>/scripts/utils/image/imageUrl.js',
    '<rootDir>/scripts/utils/image/srcsetCandidateParser.js',
    '<rootDir>/scripts/utils/image/srcsetExtractor.js',
    '<rootDir>/scripts/utils/image/srcsetParserAdapter.js',
    '<rootDir>/scripts/utils/image/srcsetUrlValidator.js',
    '<rootDir>/pages/options/DriveCloudSyncController.js',
    '<rootDir>/pages/options/MigrationScanner.js',
    '<rootDir>/pages/options/MigrationTool.js',
    '<rootDir>/pages/options/SearchableDatabaseSelector.js',
    '<rootDir>/pages/options/accountUI.js',
    '<rootDir>/pages/options/confirmDialog.js',
    '<rootDir>/pages/options/debugLogExportUI.js',
    '<rootDir>/pages/options/preferenceControls.js',
    '<rootDir>/pages/options/staticOptionMessages.js',
    '<rootDir>/pages/options/storageDataUtils.js',
    '<rootDir>/pages/popup/popupUI.js',
    '<rootDir>/pages/sidepanel/sidepanel-current-view.js',
    '<rootDir>/pages/sidepanel/sidepanel-data-transforms.js',
    '<rootDir>/scripts/auth/accountLoginInitiator.js',
    '<rootDir>/scripts/auth/auth.js',
    '<rootDir>/scripts/auth/callbackStatusView.js',
    '<rootDir>/scripts/background/handlers/accountAuthHandler.js',
    '<rootDir>/scripts/background/handlers/driveAlarmScheduler.js',
    '<rootDir>/scripts/background/handlers/driveAutoSync.js',
    '<rootDir>/scripts/background/handlers/handlerGuard.js',
    '<rootDir>/scripts/background/handlers/handlerUtils.js',
    '<rootDir>/scripts/background/handlers/highlightHandlers.js',
    '<rootDir>/scripts/background/handlers/logHandlers.js',
    '<rootDir>/scripts/background/handlers/migrationHandlers.js',
    '<rootDir>/scripts/background/handlers/sidepanelHandlers.js',
    '<rootDir>/scripts/background/handlers/toastUtils.js',
    '<rootDir>/scripts/background/services/ImageService.js',
    '<rootDir>/scripts/background/services/MigrationService.js',
    '<rootDir>/scripts/background/services/PageContentService.js',
    '<rootDir>/scripts/background/services/SaveStatusCoordinator.js',
    '<rootDir>/scripts/background/services/StorageMigrationScanner.js',
    '<rootDir>/scripts/content/converters/ConverterFactory.js',
    '<rootDir>/scripts/content/extractors/MarkdownExtractor.js',
    '<rootDir>/scripts/content/extractors/MetadataExtractor.js',
    '<rootDir>/scripts/content/extractors/NextJsDataResolver.js',
    '<rootDir>/scripts/content/extractors/NextJsExtractor.js',
    '<rootDir>/scripts/content/extractors/blocks/BbcBlockConverter.js',
    '<rootDir>/scripts/content/extractors/blocks/StoryAtomsConverter.js',
    '<rootDir>/scripts/content/extractors/temporaryImagePlaceholder.js',
    '<rootDir>/scripts/content/runtimeMessageHandlers.js',
    '<rootDir>/scripts/content/sanitizers/htmlSanitizer.js',
    '<rootDir>/pages/update-notification/update-notification.js',
  ],
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
  verbose: false,
};
