'use strict';

module.exports = {
  rootDir: '.',
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    url: 'https://notion-chrome.test/',
  },
  transform: {},
  transformIgnorePatterns: [],
  testMatch: [
    '<rootDir>/tests/native-esm/background/handlers/backgroundHandlers.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/background/services/backgroundServices.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/background/support/background-support-native-siblings.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/background/utils/backgroundUtils.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/config/configConstants.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/destinations/destinations.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/highlighter/utils/domText.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/highlighter/utils/pureUtils.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/utils/root-url-and-page-complexity.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/utils/root-utils-runtime.native-esm.test.mjs',
    '<rootDir>/tests/native-esm/utils/rootUtils.native-esm.test.mjs',
    '<rootDir>/tests/contract/native-default/ci/nativeDefaultRunnerContract.test.mjs',
    '<rootDir>/tests/contract/native-default/ci/report-native-default-runner-blockers.test.mjs',
    '<rootDir>/tests/integration/native-default/background/background-require.integration.test.mjs',
    '<rootDir>/tests/unit/native-default/config/env.test.mjs',
    '<rootDir>/tests/unit/native-default/config/messages.test.js',
    '<rootDir>/tests/unit/native-default/config/storageKeys.test.js',
    '<rootDir>/tests/unit/native-default/content/content-script.require.test.js',
    '<rootDir>/tests/unit/native-default/utils/normalizeUrl.test.js',
    '<rootDir>/tests/unit/native-default/background/buildHighlightBlocks.test.js',
    '<rootDir>/tests/unit/background/extension-lifecycle.test.js',
    '<rootDir>/tests/unit/background.test.js',
    '<rootDir>/tests/unit/native-default/utils/pageComplexityDetector.node-env.test.js',
    '<rootDir>/tests/unit/native-default/utils/splitTextForHighlight.test.js',
    '<rootDir>/tests/unit/native-default/background/processContentResult.test.js',
    '<rootDir>/tests/unit/native-default/performance/PerformanceOptimizer.advanced.test.mjs',
    '<rootDir>/tests/unit/native-default/performance/PerformanceOptimizer.batchProcessing.test.js',
    '<rootDir>/tests/unit/native-default/scripts/assert-native-esm-line-hits.test.mjs',
    '<rootDir>/tests/unit/native-default/scripts/postinstall.test.js',
    '<rootDir>/tests/unit/native-default/scripts/report-native-esm-scope-parity.test.mjs',
  ],
  setupFiles: ['<rootDir>/tests/native-esm/native-runner.setup.mjs'],
  setupFilesAfterEnv: ['<rootDir>/tests/native-esm/native-default.after-env.mjs'],
  moduleNameMapper: {
    '^@asamuzakjp/css-color$': '<rootDir>/tests/mocks/css-color.cjs',
  },
  cacheDirectory: '<rootDir>/.tmp/jest-cache-native-default',
  maxWorkers: 4,
  verbose: false,
};
