export const NOISE_SELECTORS = [
  'nav',
  'aside',
  '.sidebar',
  '.side-bar',
  '.navigation',
  '.menu',
  '.nav',
  '.navbar',
  '[role="navigation"]',
  '[role="banner"]',
  '[role="contentinfo"]',
  '[role="complementary"]',
  '.social',
  '.social-share',
  '.share-buttons',
  '.social-links',
  '[class~="social"]',
  '[class~="share"]',
  '#social-share',
  '.comments',
  '.comment-list',
  '.comment-section',
  '.comment-area',
  '.advertisement',
  '.ads',
  '.ad',
  '.banner',
  '.ad-container',
  '.related',
  '.related-posts',
  '.related-articles',
  '.recommended',
  '.widget',
  '.widgets',
  '[class^="comment-"]',
  '[class$="-comment"]',
  '[class$="-comments"]',
  '[id^="comment-"]',
  '[id$="-comment"]',
  '[id$="-comments"]',
  '[class^="recommend"]',
  '[id^="recommend"]',
  '[class^="related-"]',
  '[class$="-related"]',
  '[id^="related-"]',
  '[id$="-related"]',
  '[class^="share-"]',
  '[class$="-share"]',
  '[id^="share-"]',
  '[id$="-share"]',
];

export const EXCLUSION_SELECTORS = [
  ...NOISE_SELECTORS,
  'header:not(.article-header):not(.post-header)',
  'footer',
  '.header:not(.article-header):not(.post-header)',
  '.footer',
  '.site-header',
  '.site-footer',
  '.site-nav',
  '[class*="w-article-aside"]',
  '#module-most-popular',
  '#recommended-article-stream',
  '.stream-card',
  '.recommendation-contents',
  '.bg-toast-background',
  '#module-preference-stream',
  '[id^="taboola-stream"]',
  '.trc_rbox',
  '.trc-content-sponsored',
  '#mktbanner',
  '[class*="infinite-scroll"]',
  '[class*="endless-scroll"]',
  '[data-component="stream"]',
  '[class*="recommendation"]',
  '[class*="suggested"]',
];

export const CMS_CLEANING_RULES = {
  wordpress: {
    signals: [
      { type: 'meta', name: 'generator', pattern: /WordPress/i },
      { type: 'class', target: 'body', pattern: /wordpress/i },
    ],
    remove: ['.wpc-related-posts', '.sharedaddy', '.jp-relatedposts', '#comments', '.author-bio'],
  },
};

export const DOMAIN_CLEANING_RULES = {
  'news.qq.com': {
    container: 'div.content-left',
    remove: [],
  },
  'hk01.com': {
    container: 'main article, [role="main"] article',
    remove: ['.related-articles'],
  },
};

export const GENERIC_CLEANING_RULES = [
  ...NOISE_SELECTORS,
  'script',
  'style',
  'link[rel="stylesheet"]',
  '[class^="ad-"]',
  '[class*=" ad-"]',
  '[id^="ad-"]',
  '[id*="-ad-"]',
  '[class*="tracking"]',
  '[class*="analytics"]',
  'footer:not(.article-footer)',
  'header:not(.article-header)',
  '[hidden]',
];
