export const IMAGE_VALIDATION_CONSTANTS = {
  MAX_URL_LENGTH: 2000,
  URL_LENGTH_SAFETY_MARGIN: 500,
  URL_LENGTH_INLINE_SAFETY_MARGIN: 100,
  MAX_QUERY_PARAMS: 10,
  SRCSET_WIDTH_MULTIPLIER: 1000,
  MAX_BACKGROUND_URL_LENGTH: 2000,
  MIN_IMAGE_WIDTH: 550,
  MIN_IMAGE_HEIGHT: 300,
  MAX_RECURSION_DEPTH: 5,
};

export const IMAGE_VALIDATION = IMAGE_VALIDATION_CONSTANTS;

export const IMAGE_VALIDATION_CONFIG = {
  MAX_CACHE_SIZE: 500,
  CACHE_TTL: 30 * 60 * 1000,
  SUPPORTED_PROTOCOLS: ['http:', 'https:', 'data:', 'blob:'],
};

export const IMAGE_SIZE_RESOLVE = {
  PER_IMAGE_TIMEOUT_MS: 3000,
  TOTAL_BUDGET_MS: 5000,
};

export const IMAGE_LIMITS = {
  MAX_MAIN_CONTENT_IMAGES: 6,
  MAX_ADDITIONAL_IMAGES: 2,
  MAIN_CONTENT_SUFFICIENT_THRESHOLD: 2,
  MAX_GALLERY_IMAGES: 6,
  MIN_IMAGES_FOR_ARTICLE_SEARCH: 3,
  MAX_IMAGES_FROM_ARTICLE_SEARCH: 5,
  BATCH_PROCESS_THRESHOLD: 5,
};
