export const DOM_STABILITY = {
  THRESHOLD_MS: 150,
  MAX_WAIT_MS: 500,
};

export const CONTENT_QUALITY = {
  MIN_CONTENT_LENGTH: 250,
  MAX_LINK_DENSITY: 0.25,
  LIST_EXCEPTION_THRESHOLD: 8,
  DEFAULT_PAGE_TITLE: 'Untitled',
};
