name: DeepSource Poll (disabled auto-run)

# Disabled for automatic runs. Keep as manual workflow (workflow_dispatch) for
# occasional manual inspection or troubleshooting.
on:
  workflow_dispatch: {}

jobs:
  poll-deepsource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make script executable
        run: chmod +x ./.github/scripts/deepsource_poll.sh

      - name: DeepSource poll (disabled)
        run: |
          echo "DeepSource poll disabled in CI. To run manually, use workflow_dispatch and review logs."
          ./.github/scripts/deepsource_poll.sh || true

      - name: Post result as PR comment (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "Manual run: no automated comment will be posted by default."
